### ISSUE TITLE
Failed to process image Error

### ISSUE THREAD

**Issue by PTson2207** [getomni-ai/zerox#67] opened 2024-10-22 07:08 UTC
hi everyone I am experiencing zerox and got the following error, hope everyone can guide me, here are my steps:
git clone ...
pip install -e .

create file test.py with model gemini:
file_path = "./cs101.pdf" 
output_dir = "./output_test/cs101.md" 
result = asyncio.run(pyzerox.zerox(file_path=file_path, model=model, output_file_path=output_dir, custom_system_prompt=custom_system_prompt, **kwargs)) 
print(result)

I get the result: 
ERROR:root: Failed to process image Error: expected string or bytes-like object, got 'NoneType' ZeroxOutput(completion_time=15140.184, file_name='cs101', input_tokens=0, output_tokens=0, pages=[Page(content='', content_length=0, page=1)])

**Comment by pradhyumna85** [comment] 2024-10-22 15:13
duplicate of #49 , #58

**Comment by PTson2207** [comment] 2024-10-23 06:35
Sorry, but I know zerox only supports .pdf files. But the file type I uploaded is cs101.pdf with the link at: https://omni-demo-data.s3.amazonaws.com/test/cs101.pdf

**Comment by ummm288** [comment] 2024-10-24 21:10
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by ZisuWang** [comment] 2024-10-25 02:42
It seems that Google has changed their LLM endpoints. For example, to use gemini 1.5 pro, you should specify model as `model = "gemini/gemini-1.5-pro-002"` instead of `model = "gemini/gemini-1.5-pro"`

**Closed** 2024-10-25 03:41 UTC
